version: '3'

volumes:
  produto-ms-data: { }

services:
  controle-financeiro:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: heycristhian/controle-financeiro
    container_name: controle-financeiro
    ports:
      - "8080:8080"
#    depends_on:
#      - ""

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24